version: '3.9'

services:
  runner:
    build: .
    environment:
      - ORGANIZATION=<YOUR-GITHUB-ORGANIZATION>
      - ACCESS_TOKEN=<YOUR-GITHUB-ACCESS-TOKEN>
      - REGISTRY_URL=<YOUR-REGISTRY-URL>
