version: '3'

services:
  runner:
    image: pjabadesco/docker-github-action-runner:0.49
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    environment:
      - ORGANIZATION=<YOUR-GITHUB-ORGANIZATION>
      - ACCESS_TOKEN=<YOUR-GITHUB-ACCESS-TOKEN>
      - REGISTRY_URL=192.168.0.1:5000
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kube:/home/docker/.kube
      - work:/home/docker/actions-runner/_work
volumes:
  kube: null
  work: null
